-- +goose Up
CREATE TABLE IF NOT EXISTS source_documents (id TEXT PRIMARY KEY, original_name TEXT NOT NULL, media_type TEXT NOT NULL, sha256 TEXT NOT NULL UNIQUE, original_path TEXT NOT NULL, parsed_path TEXT, status TEXT NOT NULL, parser_version TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS source_chunks (id TEXT PRIMARY KEY, document_id TEXT NOT NULL REFERENCES source_documents(id), chunk_index INTEGER NOT NULL, text TEXT NOT NULL, page_number INTEGER, heading_path TEXT, char_start INTEGER NOT NULL, char_end INTEGER NOT NULL, content_hash TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS wiki_pages (id TEXT PRIMARY KEY, slug TEXT NOT NULL UNIQUE, page_type TEXT NOT NULL, title TEXT NOT NULL, summary TEXT NOT NULL, status TEXT NOT NULL, current_revision INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS wiki_sections (id TEXT PRIMARY KEY, page_id TEXT NOT NULL REFERENCES wiki_pages(id), heading TEXT NOT NULL, position INTEGER NOT NULL, summary TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS compilation_runs (id TEXT PRIMARY KEY, document_id TEXT NOT NULL REFERENCES source_documents(id), status TEXT NOT NULL, analyze_json TEXT, candidates_json TEXT, plan_json TEXT, validation_json TEXT, apply_result_json TEXT, diff_json TEXT, model TEXT, prompt_version TEXT, usage_json TEXT, duration_ms INTEGER, error TEXT, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS wiki_claims (id TEXT PRIMARY KEY, page_id TEXT NOT NULL REFERENCES wiki_pages(id), section_id TEXT REFERENCES wiki_sections(id), text TEXT NOT NULL, claim_type TEXT NOT NULL, status TEXT NOT NULL, created_by_run_id TEXT NOT NULL REFERENCES compilation_runs(id), updated_by_run_id TEXT NOT NULL REFERENCES compilation_runs(id));
CREATE TABLE IF NOT EXISTS claim_evidence (claim_id TEXT NOT NULL REFERENCES wiki_claims(id), source_chunk_id TEXT NOT NULL REFERENCES source_chunks(id), relation TEXT NOT NULL, note TEXT, PRIMARY KEY (claim_id, source_chunk_id, relation));
CREATE TABLE IF NOT EXISTS wiki_links (source_page_id TEXT NOT NULL REFERENCES wiki_pages(id), target_page_id TEXT NOT NULL REFERENCES wiki_pages(id), relation TEXT NOT NULL, created_by_run_id TEXT NOT NULL REFERENCES compilation_runs(id), PRIMARY KEY (source_page_id, target_page_id, relation));
CREATE TABLE IF NOT EXISTS wiki_revisions (page_id TEXT NOT NULL REFERENCES wiki_pages(id), revision_number INTEGER NOT NULL, compilation_run_id TEXT NOT NULL REFERENCES compilation_runs(id), snapshot_json TEXT NOT NULL, change_summary TEXT NOT NULL, created_at TEXT NOT NULL, PRIMARY KEY (page_id, revision_number));
CREATE TABLE IF NOT EXISTS retrieval_traces (id TEXT PRIMARY KEY, normalized_query TEXT NOT NULL, trace_json TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS conversations (id TEXT PRIMARY KEY, title TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS messages (id TEXT PRIMARY KEY, conversation_id TEXT NOT NULL REFERENCES conversations(id), role TEXT NOT NULL, content TEXT NOT NULL, metadata_json TEXT, created_at TEXT NOT NULL);
-- +goose Down
DROP TABLE messages; DROP TABLE conversations; DROP TABLE retrieval_traces; DROP TABLE wiki_revisions; DROP TABLE wiki_links; DROP TABLE claim_evidence; DROP TABLE wiki_claims; DROP TABLE compilation_runs; DROP TABLE wiki_sections; DROP TABLE wiki_pages; DROP TABLE source_chunks; DROP TABLE source_documents;
