import { useMutation, useQuery } from '@tanstack/react-query'
import { CheckCircle2, Database, RefreshCw, Save } from 'lucide-react'
import { useEffect, useState } from 'react'
import { archiveKnowledgeBase, getConfig, reindex, saveSettings, updateKnowledgeBase, type SettingsInput } from '../../api/contracts'
import { useI18n } from '../../i18n'
import { useWorkspace } from '../../workspace'

const empty: SettingsInput = { llm: { base_url: 'https://oneapi-comate.baidu-int.com/v1', model: '', api_key: '', fake_fallback: false }, embedding: { base_url: 'http://127.0.0.1:11434', model: 'qwen3-embedding:0.6b', batch_size: 32 }, language: 'zh' }

export function SettingsPanel() {
  const { t, language: uiLanguage, setLanguage: setUILanguage } = useI18n()
  const workspace = useWorkspace()
  const config = useQuery({ queryKey: ['config', workspace.selectedID], queryFn: getConfig })
  const [form, setForm] = useState<SettingsInput>(empty)
  const [name, setName] = useState('')
  const [description, setDescription] = useState('')
  const [newName, setNewName] = useState('')
  const [newDescription, setNewDescription] = useState('')
  const [newLanguage, setNewLanguage] = useState<'zh' | 'en'>('zh')
  const save = useMutation({ mutationFn: saveSettings, onSuccess: () => void config.refetch() })
  const rebuild = useMutation({ mutationFn: reindex })
  const currentName = workspace.current?.name ?? ''
  const currentDescription = workspace.current?.description ?? ''
  useEffect(() => { if (!config.data) return; setForm({ llm: { base_url: config.data.settings.llm.base_url, model: config.data.settings.llm.model, api_key: '', fake_fallback: Boolean(config.data.settings.llm.fake_fallback) }, embedding: { base_url: config.data.settings.embedding.base_url, model: config.data.settings.embedding.model, batch_size: config.data.settings.embedding.batch_size ?? 32 }, language: config.data.settings.language }); }, [config.data])
  useEffect(() => { setName(currentName); setDescription(currentDescription) }, [currentName, currentDescription])
  const patch = (section: 'llm' | 'embedding', key: string, value: string | boolean | number) => setForm(current => {
    if (section === 'llm') return { ...current, llm: { ...current.llm, [key]: value } as SettingsInput['llm'] }
    return { ...current, embedding: { ...current.embedding, [key]: value } as SettingsInput['embedding'] }
  })
  const saveWorkspace = useMutation({ mutationFn: () => updateKnowledgeBase(workspace.selectedID, { name, description, language: form.language }), onSuccess: () => void workspace.refresh() })
  const createWorkspace = useMutation({ mutationFn: () => workspace.create(newName, newDescription, newLanguage), onSuccess: () => { setNewName(''); setNewDescription(''); setNewLanguage('zh') } })
  const archive = useMutation({ mutationFn: () => archiveKnowledgeBase(workspace.selectedID), onSuccess: async () => { await workspace.refresh(); workspace.select('default') } })
  return <main className="work-page settings-page"><header className="page-head"><div><p className="eyebrow">{t('Runtime configuration')} · {workspace.current?.name}</p><h1>{t('Settings')}</h1><p className="muted">{t('Baidu OneAPI powers Compiler, Query, and Chat. Local Ollama powers Wiki and Source embeddings.')}</p></div><button className="primary-command" disabled={save.isPending || config.isLoading} onClick={() => save.mutate(form)}><Save size={16} />{t(save.isPending ? 'Saving...' : 'Save')}</button></header>
    {config.isError && <div className="notice error"><span>{t('Could not load provider settings.')}</span><button onClick={() => void config.refetch()}><RefreshCw size={14} />{t('Retry')}</button></div>}
    {save.isSuccess && <div className="notice success"><CheckCircle2 size={16} />{t('Settings saved')} {t('Reindex after changing the embedding provider.')}</div>}{save.isError && <div className="notice error">{save.error.message}</div>}
    <section className="provider-panel workspace-settings"><div className="panel-title"><span>{t('Current knowledge base')}</span><span className="status status-active">{workspace.current?.language === 'zh' ? t('中文 output') : t('English output')}</span></div><label>{t('Name')}<input value={name} onChange={event => setName(event.target.value)} /></label><label>{t('Description')}<input value={description} onChange={event => setDescription(event.target.value)} /></label><label>{t('UI language')}<select value={uiLanguage} onChange={event => setUILanguage(event.target.value as 'zh' | 'en')}><option value="zh">{t('Chinese')}</option><option value="en">{t('English')}</option></select></label><label>{t('Output language')}<select value={form.language} onChange={event => setForm(current => ({ ...current, language: event.target.value as 'zh' | 'en' }))}><option value="zh">{t('Chinese')}</option><option value="en">{t('English')}</option></select></label><div className="settings-actions"><button className="primary-command" disabled={saveWorkspace.isPending} onClick={() => saveWorkspace.mutate()}>{t(saveWorkspace.isPending ? 'Saving...' : 'Save')}</button>{workspace.selectedID !== 'default' && <button disabled={archive.isPending} onClick={() => archive.mutate()}>{t('Archive')}</button>}</div></section>
    <section className="provider-panel workspace-settings"><div className="panel-title"><span>{t('Create knowledge base')}</span><small>{t('New knowledge base')}</small></div><label>{t('Name')}<input value={newName} onChange={event => setNewName(event.target.value)} placeholder={t('Knowledge base name')} /></label><label>{t('Description')}<input value={newDescription} onChange={event => setNewDescription(event.target.value)} placeholder={t('Knowledge base description')} /></label><label>{t('Output language')}<select value={newLanguage} onChange={event => setNewLanguage(event.target.value as 'zh' | 'en')}><option value="zh">{t('Chinese')}</option><option value="en">{t('English')}</option></select></label><button className="primary-command" disabled={createWorkspace.isPending || !newName.trim()} onClick={() => createWorkspace.mutate()}><Database size={16} />{t(createWorkspace.isPending ? 'Creating...' : 'Create')}</button>{createWorkspace.isSuccess && <div className="notice success">{t('Knowledge base created')}</div>}{createWorkspace.isError && <div className="notice error">{createWorkspace.error.message}</div>}</section>
    <div className="settings-grid"><ProviderForm t={t} title="LLM · Baidu OneAPI" status={Boolean(config.data?.providers.compiler_llm.configured && config.data?.providers.chat_llm.configured)} values={form.llm} keySet={config.data?.settings.llm.api_key_set} onChange={(key, value) => patch('llm', key, value)} fake /><ProviderForm t={t} title="Embedding · Ollama" status={config.data?.providers.embedding.configured} values={form.embedding} onChange={(key, value) => patch('embedding', key, value)} embedding /></div>
    <section className="maintenance"><div><Database size={19} /><span><strong>{t('Retrieval indexes')}</strong><small>{t('Rebuild FTS, Wiki vectors, and Source evidence vectors from SQLite.')}</small></span></div><button disabled={rebuild.isPending} onClick={() => rebuild.mutate()}>{t(rebuild.isPending ? 'Reindexing...' : 'Reindex now')}</button>{rebuild.data && <p>{rebuild.data.wiki_passages} {t('Wiki passages')} · {rebuild.data.source_chunks} {t('Source chunks')} · {rebuild.data.embeddings_made} {t('embeddings')} {t('generated')}</p>}{rebuild.isError && <p className="error-text">{rebuild.error.message}</p>}</section>
  </main>
}

function ProviderForm({ t, title, status, values, keySet, onChange, fake = false, embedding = false }: { t: (key: string) => string; title: string; status?: boolean; values: Record<string, string | boolean | number>; keySet?: boolean; onChange: (key: string, value: string | boolean | number) => void; fake?: boolean; embedding?: boolean }) { return <section className="provider-panel"><div className="panel-title"><span>{title}</span><span className={`status ${status ? 'status-applied' : 'status-pending'}`}>{status ? t('configured') : t('not configured')}</span></div><label>{t(embedding ? 'Ollama Base URL' : 'LLM Base URL')}<input value={String(values.base_url)} placeholder={embedding ? 'http://127.0.0.1:11434' : 'https://oneapi-comate.baidu-int.com/v1'} onChange={event => onChange('base_url', event.target.value)} /></label><label>{t('Model')}<input value={String(values.model)} placeholder={embedding ? 'qwen3-embedding:0.6b' : t('model name')} onChange={event => onChange('model', event.target.value)} /></label>{!embedding && <label>{t('API key')}<input type="password" value={String(values.api_key)} placeholder={keySet ? t('Stored; leave blank to keep') : t('Required for OneAPI')} onChange={event => onChange('api_key', event.target.value)} /></label>}{fake && <label className="toggle"><input type="checkbox" checked={Boolean(values.fake_fallback)} onChange={event => onChange('fake_fallback', event.target.checked)} /><span>{t('Deterministic development fallback')}</span></label>}{embedding && <label>{t('Batch size')}<input type="number" min="1" value={Number(values.batch_size)} onChange={event => onChange('batch_size', Number(event.target.value))} /></label>}</section> }
