import { useMutation, useQuery } from '@tanstack/react-query'
import { CheckCircle2, Database, RefreshCw, Save } from 'lucide-react'
import { useEffect, useState } from 'react'
import { getConfig, reindex, saveSettings, type SettingsInput } from '../../api/contracts'

const empty: SettingsInput = { llm: { base_url: 'https://oneapi-comate.baidu-int.com/v1', model: '', api_key: '', fake_fallback: false }, embedding: { base_url: 'http://127.0.0.1:11434', model: 'qwen3-embedding:0.6b', batch_size: 32 } }

export function SettingsPanel() {
  const config = useQuery({ queryKey: ['config'], queryFn: getConfig })
  const [form, setForm] = useState<SettingsInput>(empty)
  const save = useMutation({ mutationFn: saveSettings, onSuccess: () => void config.refetch() })
  const rebuild = useMutation({ mutationFn: reindex })
  useEffect(() => { if (!config.data) return; setForm({ llm: { base_url: config.data.settings.llm.base_url, model: config.data.settings.llm.model, api_key: '', fake_fallback: Boolean(config.data.settings.llm.fake_fallback) }, embedding: { base_url: config.data.settings.embedding.base_url, model: config.data.settings.embedding.model, batch_size: config.data.settings.embedding.batch_size ?? 32 } }) }, [config.data])
  const patch = (section: keyof SettingsInput, key: string, value: string | boolean | number) => setForm(current => ({ ...current, [section]: { ...current[section], [key]: value } }))
  return <main className="work-page settings-page"><header className="page-head"><div><p className="eyebrow">Runtime configuration</p><h1>Settings</h1><p className="muted">Baidu OneAPI powers Compiler, Query, and Chat. Local Ollama powers Wiki and Source embeddings.</p></div><button className="primary-command" disabled={save.isPending || config.isLoading} onClick={() => save.mutate(form)}><Save size={16} />{save.isPending ? 'Saving...' : 'Save settings'}</button></header>
    {config.isError && <div className="notice error"><span>Could not load provider settings.</span><button onClick={() => void config.refetch()}><RefreshCw size={14} />Retry</button></div>}
    {save.isSuccess && <div className="notice success"><CheckCircle2 size={16} />Settings saved and adapters updated. Reindex after changing the embedding provider.</div>}{save.isError && <div className="notice error">{save.error.message}</div>}
    <div className="settings-grid"><ProviderForm title="LLM · Baidu OneAPI" status={Boolean(config.data?.providers.compiler_llm.configured && config.data?.providers.chat_llm.configured)} values={form.llm} keySet={config.data?.settings.llm.api_key_set} onChange={(key, value) => patch('llm', key, value)} fake /><ProviderForm title="Embedding · Ollama" status={config.data?.providers.embedding.configured} values={form.embedding} onChange={(key, value) => patch('embedding', key, value)} embedding /></div>
    <section className="maintenance"><div><Database size={19} /><span><strong>Retrieval indexes</strong><small>Rebuild FTS, Wiki vectors, and Source evidence vectors from SQLite.</small></span></div><button disabled={rebuild.isPending} onClick={() => rebuild.mutate()}>{rebuild.isPending ? 'Reindexing...' : 'Reindex now'}</button>{rebuild.data && <p>{rebuild.data.wiki_passages} Wiki passages · {rebuild.data.source_chunks} Source chunks · {rebuild.data.embeddings_made} embeddings generated</p>}{rebuild.isError && <p className="error-text">{rebuild.error.message}</p>}</section>
  </main>
}

function ProviderForm({ title, status, values, keySet, onChange, fake = false, embedding = false }: { title: string; status?: boolean; values: Record<string, string | boolean | number>; keySet?: boolean; onChange: (key: string, value: string | boolean | number) => void; fake?: boolean; embedding?: boolean }) { return <section className="provider-panel"><div className="panel-title"><span>{title}</span><span className={`status ${status ? 'status-applied' : 'status-pending'}`}>{status ? 'configured' : 'not configured'}</span></div><label>{embedding ? 'Ollama Base URL' : 'LLM Base URL'}<input value={String(values.base_url)} placeholder={embedding ? 'http://127.0.0.1:11434' : 'https://oneapi-comate.baidu-int.com/v1'} onChange={event => onChange('base_url', event.target.value)} /></label><label>Model<input value={String(values.model)} placeholder={embedding ? 'qwen3-embedding:0.6b' : 'model name'} onChange={event => onChange('model', event.target.value)} /></label>{!embedding && <label>API key<input type="password" value={String(values.api_key)} placeholder={keySet ? 'Stored; leave blank to keep' : 'Required for OneAPI'} onChange={event => onChange('api_key', event.target.value)} /></label>}{fake && <label className="toggle"><input type="checkbox" checked={Boolean(values.fake_fallback)} onChange={event => onChange('fake_fallback', event.target.checked)} /><span>Deterministic development fallback</span></label>}{embedding && <label>Batch size<input type="number" min="1" value={Number(values.batch_size)} onChange={event => onChange('batch_size', Number(event.target.value))} /></label>}</section> }
