import { createContext, useCallback, useContext, useMemo, useState } from 'react'

export type Language = 'zh' | 'en'
const storageKey = 'llm-wiki-language'
const messages: Record<Language, Record<string, string>> = {
  en: {
    Wiki: 'Wiki', Sources: 'Sources', Compilation: 'Compilation', Search: 'Search', Query: 'Query', Chat: 'Chat', Settings: 'Settings',
    'Knowledge bases': 'Knowledge bases', 'Switch knowledge base': 'Switch knowledge base', 'New knowledge base': 'New knowledge base',
    'UI language': 'UI language', 'Output language': 'Model output language', Chinese: '中文', English: 'English', Save: 'Save', Create: 'Create', Archive: 'Archive',
    'Current knowledge base': 'Current knowledge base', 'Create knowledge base': 'Create knowledge base', 'Knowledge base created': 'Knowledge base created and selected.', 'Knowledge base saved': 'Knowledge base saved.', 'Knowledge base archived': 'Knowledge base archived.', 'Name is required': 'Name is required', 'Knowledge base name': 'Knowledge base name', 'Knowledge base description': 'Knowledge base description', 'Creating...': 'Creating...',
    'Settings saved': 'Settings saved and adapters updated.', 'Loading...': 'Loading...', Retry: 'Retry', Dismiss: 'Dismiss', Ask: 'Ask', Model: 'Model', 'No data yet': 'No data yet', offline: 'offline', checking: 'checking', Workspace: 'Workspace', Page: 'Page', Chars: 'Chars', src: 'src', 'Wiki passages': 'Wiki passages',
    'Compiled Wiki': 'Compiled Wiki', Concepts: 'Concepts', Entities: 'Entities', Topics: 'Topics', 'Loading pages...': 'Loading pages...', 'Wiki API is unavailable.': 'Wiki API is unavailable.', 'No compiled pages yet.': 'No compiled pages yet.',
    'Loading compiled knowledge...': 'Loading compiled knowledge...', 'This Wiki page could not be loaded.': 'This Wiki page could not be loaded.', 'This page is': 'This page is', 'and is no longer part of the active Wiki.': 'and is no longer part of the active Wiki.', 'Open canonical page:': 'Open canonical page:', Revision: 'Revision', claims: 'claims', sources: 'sources', Knowledge: 'Knowledge', Revisions: 'Revisions', Disputed: 'Disputed', Connections: 'Connections', Links: 'Links', Backlinks: 'Backlinks', None: 'None', 'Source Inspector': 'Source Inspector', Chunk: 'Chunk', Relation: 'Relation', Media: 'Media', 'Select a citation to inspect the exact Source Chunk and its original location.': 'Select a citation to inspect the exact Source Chunk and its original location.', 'Open Sources': 'Open Sources', 'Close citation inspector': 'Close citation inspector', 'Open citation inspector': 'Open citation inspector',
    'Evidence layer': 'Evidence layer', 'Preserved originals, parser status, stable chunks, and compilation entry points.': 'Preserved originals, parser status, stable chunks, and compilation entry points.', 'Upload source': 'Upload source', Parsing: 'Parsing...', 'Duplicate detected. Existing Source reused.': 'Duplicate detected. Existing Source reused.', 'stable chunks parsed.': 'stable chunks parsed.', 'Source library': 'Source library', 'Loading Sources...': 'Loading Sources...', 'Could not load Sources.': 'Could not load Sources.', 'Upload Markdown, TXT, or a text PDF to begin.': 'Upload Markdown, TXT, or a text PDF to begin.', 'Compiling...': 'Compiling...', 'Compile Source': 'Compile Source', 'Parser failed. The original Source remains preserved.': 'Parser failed. The original Source remains preserved.', 'Open run': 'Open run', chunks: 'chunks', 'compiled claims': 'compiled claims', 'parser status': 'parser status', 'Source chunks': 'Source chunks', 'stable evidence IDs': 'stable evidence IDs', 'Loading chunks...': 'Loading chunks...', 'Could not load chunks.': 'Could not load chunks.', 'No chunks were produced for this Source.': 'No chunks were produced for this Source.', 'Select a Source to inspect parsing and evidence.': 'Select a Source to inspect parsing and evidence.', 'Citation Inspector': 'Citation Inspector', 'Locating citation...': 'Locating citation...', 'Citation could not be loaded.': 'Citation could not be loaded.', 'Chunk ID': 'Chunk ID', 'Source ID': 'Source ID', Index: 'Index', 'Choose a chunk or open a citation to inspect its exact source location.': 'Choose a chunk or open a citation to inspect its exact source location.',
    'Knowledge compiler': 'Knowledge compiler', 'Observe Parse → Analyze → Match → Plan → Validate → Apply without hidden writes.': 'Observe Parse → Analyze → Match → Plan → Validate → Apply without hidden writes.', 'Source to compile': 'Source to compile', 'Select parsed Source': 'Select parsed Source', Running: 'Running...', Compile: 'Compile', 'Compilation runs': 'Compilation runs', 'Loading runs...': 'Loading runs...', 'No compilation runs yet.': 'No compilation runs yet.', 'Retry render': 'Retry render', captured: 'captured', pending: 'pending', 'No output captured at this stage.': 'No output captured at this stage.', 'Existing Wiki Candidates': 'Existing Wiki Candidates', 'claim actions': 'claim actions', 'Plan passed schema and domain validation.': 'Plan passed schema and domain validation.', 'Select a run to inspect the compiler pipeline.': 'Select a run to inspect the compiler pipeline.', Open: 'Open', added: 'added', changed: 'changed', removed: 'removed', 'unknown model': 'unknown model', Validation: 'Validation', 'Diff & Apply': 'Diff & Apply', Analyze: 'Analyze', Plan: 'Plan',
    'Hybrid retrieval': 'Hybrid retrieval', 'Search compiled Wiki': 'Search compiled Wiki', 'Wiki passages lead retrieval; Source chunks are added only as evidence fallback.': 'Wiki passages lead retrieval; Source chunks are added only as evidence fallback.', 'Search a concept, method, or claim': 'Search a concept, method, or claim', 'Search failed': 'Search failed', 'Searching FTS and vectors...': 'Searching FTS and vectors...', 'Ranked candidates': 'Ranked candidates', pages: 'pages', 'In context': 'In context', Dropped: 'Dropped', '1-hop link expansion': '1-hop link expansion', 'No active Wiki candidate matched this query.': 'No active Wiki candidate matched this query.', 'Final context': 'Final context', items: 'items', chars: 'chars', 'Retrieval trace': 'Retrieval trace', 'FTS candidates': 'FTS candidates', 'Vector candidates': 'Vector candidates', 'Link expansion': 'Link expansion', 'Final candidates': 'Final candidates', 'Context IDs': 'Context IDs', none: 'none', Expansion: 'Expansion', Final: 'Final', Vector: 'Vector',
    'Grounded query': 'Grounded query', 'Ask once, cite the Wiki': 'Ask once, cite the Wiki', 'Answers use the same hybrid retrieval context as Search.': 'Answers use the same hybrid retrieval context as Search.', 'Ask a grounded question': 'Ask a grounded question', 'Retrieving Wiki context and generating a cited answer...': 'Retrieving Wiki context and generating a cited answer...', Answer: 'Answer', 'Source citations': 'Source citations', 'No source evidence': 'No source evidence', Trace: 'Trace', 'Wiki references': 'Wiki references', 'Context used': 'Context used',
    'Persistent conversation': 'Persistent conversation', 'Ask the compiled Wiki': 'Ask the compiled Wiki', 'Recent history is rewritten into a standalone query; every turn preserves its trace and citations.': 'Recent history is rewritten into a standalone query; every turn preserves its trace and citations.', 'Restoring conversation...': 'Restoring conversation...', You: 'You', 'Wiki answer': 'Wiki answer', 'Retrieved as:': 'Retrieved as:', 'not recorded': 'not recorded', 'Wiki answer · streaming': 'Wiki answer · streaming', 'Ask a question to start a persisted conversation.': 'Ask a question to start a persisted conversation.', 'Ask a question about the Wiki': 'Ask a question about the Wiki', Working: 'Working', Send: 'Send', 'Request failed': 'Request failed', 'Wiki:': 'Wiki:', 'context items': 'context items',
    'Runtime configuration': 'Runtime configuration', 'Baidu OneAPI powers Compiler, Query, and Chat. Local Ollama powers Wiki and Source embeddings.': 'Baidu OneAPI powers Compiler, Query, and Chat. Local Ollama powers Wiki and Source embeddings.', 'Saving...': 'Saving...', 'Could not load provider settings.': 'Could not load provider settings.', 'Reindex after changing the embedding provider.': 'Reindex after changing the embedding provider.', Name: 'Name', Description: 'Description', '中文 output': '中文 output', 'English output': 'English output', configured: 'configured', 'not configured': 'not configured', 'LLM Base URL': 'LLM Base URL', 'Ollama Base URL': 'Ollama Base URL', 'API key': 'API key', 'Stored; leave blank to keep': 'Stored; leave blank to keep', 'Required for OneAPI': 'Required for OneAPI', 'model name': 'model name', 'Deterministic development fallback': 'Deterministic development fallback', 'Batch size': 'Batch size', 'Retrieval indexes': 'Retrieval indexes', 'Rebuild FTS, Wiki vectors, and Source evidence vectors from SQLite.': 'Rebuild FTS, Wiki vectors, and Source evidence vectors from SQLite.', Reindexing: 'Reindexing...', 'Reindex now': 'Reindex now', embeddings: 'embeddings', generated: 'generated',
  },
  zh: {
    Wiki: '知识 Wiki', Sources: '来源', Compilation: '编译', Search: '搜索', Query: '问答', Chat: '对话', Settings: '设置',
    'Knowledge bases': '知识库', 'Switch knowledge base': '切换知识库', 'New knowledge base': '新建知识库',
    'UI language': '界面语言', 'Output language': '模型输出语言', Chinese: '中文', English: 'English', Save: '保存', Create: '创建', Archive: '归档',
    'Current knowledge base': '当前知识库', 'Create knowledge base': '创建知识库', 'Knowledge base created': '知识库已创建并选中。', 'Knowledge base saved': '知识库已保存。', 'Knowledge base archived': '知识库已归档。', 'Name is required': '名称为必填项', 'Knowledge base name': '知识库名称', 'Knowledge base description': '知识库描述', 'Creating...': '创建中...',
    'Settings saved': '设置已保存，适配器已更新。', 'Loading...': '加载中...', Retry: '重试', Dismiss: '关闭', Ask: '提问', Model: '模型', 'No data yet': '暂无数据', offline: '离线', checking: '检查中', Workspace: '工作区', Page: '页码', Chars: '字符', src: '来源', 'Wiki passages': 'Wiki 分段',
    'Compiled Wiki': '已编译 Wiki', Concepts: '概念', Entities: '实体', Topics: '主题', 'Loading pages...': '正在加载页面...', 'Wiki API is unavailable.': 'Wiki API 不可用。', 'No compiled pages yet.': '还没有已编译页面。', 'Loading compiled knowledge...': '正在加载编译后的知识...', 'This Wiki page could not be loaded.': '无法加载此 Wiki 页面。', 'This page is': '此页面当前为', 'and is no longer part of the active Wiki.': '，已不再属于活跃 Wiki。', 'Open canonical page:': '打开规范页面：', Revision: '修订版', claims: '条声明', sources: '个来源', Knowledge: '知识', Revisions: '修订历史', Disputed: '有争议', Connections: '关联', Links: '链接', Backlinks: '反向链接', None: '无', 'Source Inspector': '来源检查器', Chunk: '分块', Relation: '关系', Media: '媒体', 'Select a citation to inspect the exact Source Chunk and its original location.': '选择引用以查看准确的来源分块和原始位置。', 'Open Sources': '打开来源', 'Close citation inspector': '关闭引用检查器', 'Open citation inspector': '打开引用检查器',
    'Evidence layer': '证据层', 'Preserved originals, parser status, stable chunks, and compilation entry points.': '保留原始文件、解析状态、稳定分块和编译入口。', 'Upload source': '上传来源', Parsing: '解析中...', 'Duplicate detected. Existing Source reused.': '检测到重复内容，已复用现有来源。', 'stable chunks parsed.': '个稳定分块已解析。', 'Source library': '来源库', 'Loading Sources...': '正在加载来源...', 'Could not load Sources.': '无法加载来源。', 'Upload Markdown, TXT, or a text PDF to begin.': '上传 Markdown、TXT 或文本 PDF 开始。', 'Compiling...': '编译中...', 'Compile Source': '编译来源', 'Parser failed. The original Source remains preserved.': '解析失败，原始来源仍已保留。', 'Open run': '打开运行记录', chunks: '个分块', 'compiled claims': '条已编译声明', 'parser status': '解析状态', 'Source chunks': '来源分块', 'stable evidence IDs': '稳定证据 ID', 'Loading chunks...': '正在加载分块...', 'Could not load chunks.': '无法加载分块。', 'No chunks were produced for this Source.': '此来源没有生成分块。', 'Select a Source to inspect parsing and evidence.': '选择来源以检查解析和证据。', 'Citation Inspector': '引用检查器', 'Locating citation...': '正在定位引用...', 'Citation could not be loaded.': '无法加载引用。', 'Chunk ID': '分块 ID', 'Source ID': '来源 ID', Index: '索引', 'Choose a chunk or open a citation to inspect its exact source location.': '选择分块或打开引用以检查准确来源位置。',
    'Delete source': '删除来源', 'Deleting...': '删除中...', 'Delete this source and every page compiled only from it? This cannot be undone.': '删除该来源，以及仅由它编译出的所有页面？此操作不可撤销。', 'Delete page': '删除页面', 'Delete this page and its links? This cannot be undone.': '删除该页面及其链接？此操作不可撤销。',
    'Knowledge compiler': '知识编译器', 'Observe Parse → Analyze → Match → Plan → Validate → Apply without hidden writes.': '观察 Parse → Analyze → Match → Plan → Validate → Apply，所有写入均可见。', 'Source to compile': '待编译来源', 'Select parsed Source': '选择已解析来源', Running: '运行中...', Compile: '编译', 'Compilation runs': '编译运行', 'Loading runs...': '正在加载运行记录...', 'No compilation runs yet.': '还没有编译运行记录。', 'Retry render': '重试渲染', captured: '已记录', pending: '待处理', 'No output captured at this stage.': '此阶段没有输出。', 'Existing Wiki Candidates': '已有 Wiki 候选', 'claim actions': '条声明操作', 'Plan passed schema and domain validation.': '计划已通过 schema 和领域校验。', 'Select a run to inspect the compiler pipeline.': '选择运行记录以检查编译流程。', Open: '打开', added: '新增', changed: '变更', removed: '移除', 'unknown model': '未知模型', Validation: '校验', 'Diff & Apply': '差异与应用', Analyze: '分析', Plan: '计划',
    'Hybrid retrieval': '混合检索', 'Search compiled Wiki': '搜索已编译 Wiki', 'Wiki passages lead retrieval; Source chunks are added only as evidence fallback.': '优先检索 Wiki 分段，来源分块仅作为证据回退。', 'Search a concept, method, or claim': '搜索概念、方法或声明', 'Search failed': '搜索失败', 'Searching FTS and vectors...': '正在搜索全文索引和向量...', 'Ranked candidates': '排序候选', pages: '个页面', 'In context': '已进入上下文', Dropped: '已丢弃', '1-hop link expansion': '一跳链接扩展', 'No active Wiki candidate matched this query.': '没有匹配的活跃 Wiki 候选。', 'Final context': '最终上下文', items: '项', chars: '字符', 'Retrieval trace': '检索轨迹', 'FTS candidates': '全文候选', 'Vector candidates': '向量候选', 'Link expansion': '链接扩展', 'Final candidates': '最终候选', 'Context IDs': '上下文 ID', none: '无', Expansion: '扩展', Final: '最终分数', Vector: '向量',
    'Grounded query': '有依据问答', 'Ask once, cite the Wiki': '一次提问，引用 Wiki', 'Answers use the same hybrid retrieval context as Search.': '回答使用与搜索相同的混合检索上下文。', 'Ask a grounded question': '提出一个有依据的问题', 'Retrieving Wiki context and generating a cited answer...': '正在检索 Wiki 上下文并生成带引用的回答...', Answer: '回答', 'Source citations': '来源引用', 'No source evidence': '没有来源证据', Trace: '轨迹', 'Wiki references': 'Wiki 引用', 'Context used': '使用的上下文',
    'Persistent conversation': '持久化对话', 'Ask the compiled Wiki': '询问已编译 Wiki', 'Recent history is rewritten into a standalone query; every turn preserves its trace and citations.': '最近历史会改写为独立查询，每轮都保留轨迹和引用。', 'Restoring conversation...': '正在恢复对话...', You: '你', 'Wiki answer': 'Wiki 回答', 'Retrieved as:': '检索查询：', 'not recorded': '未记录', 'Wiki answer · streaming': 'Wiki 回答 · 流式中', 'Ask a question to start a persisted conversation.': '提问以开始持久化对话。', 'Ask a question about the Wiki': '询问 Wiki 中的问题', Working: '处理中', Send: '发送', 'Request failed': '请求失败', 'Wiki:': 'Wiki：', 'context items': '项上下文',
    'Runtime configuration': '运行时配置', 'Baidu OneAPI powers Compiler, Query, and Chat. Local Ollama powers Wiki and Source embeddings.': 'Baidu OneAPI 为编译器、问答和对话提供 LLM，本地 Ollama 提供 Wiki 与来源向量。', 'Saving...': '保存中...', 'Could not load provider settings.': '无法加载 Provider 设置。', 'Reindex after changing the embedding provider.': '修改 Embedding Provider 后请重新索引。', Name: '名称', Description: '描述', '中文 output': '中文输出', 'English output': '英文输出', configured: '已配置', 'not configured': '未配置', 'LLM Base URL': 'LLM Base URL', 'Ollama Base URL': 'Ollama Base URL', 'API key': 'API Key', 'Stored; leave blank to keep': '已保存，留空以保留', 'Required for OneAPI': 'OneAPI 必填', 'model name': '模型名称', 'Deterministic development fallback': '确定性开发回退', 'Batch size': '批大小', 'Retrieval indexes': '检索索引', 'Rebuild FTS, Wiki vectors, and Source evidence vectors from SQLite.': '从 SQLite 重建全文、Wiki 向量和来源证据向量。', Reindexing: '重新索引中...', 'Reindex now': '立即重建索引', embeddings: '个向量', generated: '已生成',
  },
}

type I18nValue = { language: Language; setLanguage: (language: Language) => void; t: (key: string) => string }
const I18nContext = createContext<I18nValue | null>(null)

export function I18nProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => window.localStorage.getItem(storageKey) === 'zh' ? 'zh' : 'en')
  const setLanguage = useCallback((next: Language) => { setLanguageState(next); window.localStorage.setItem(storageKey, next) }, [])
  const value = useMemo(() => ({ language, setLanguage, t: (key: string) => messages[language][key] || key }), [language, setLanguage])
  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>
}

export function useI18n(): I18nValue {
  const value = useContext(I18nContext)
  if (!value) throw new Error('useI18n must be used inside I18nProvider')
  return value
}
